name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Beri Izin Eksekusi Gradle
      run: chmod +x ./gradlew

    - name: Proses Build APK
      run: ./gradlew assembleDebug

    - name: Simpan dan Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Arthafin-APK
        path: app/build/outputs/apk/debug/*.apk
